<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import AdminButton from "../components/form/AdminButton.vue";
import AdminDateField from "../components/form/AdminDateField.vue";
import RevenueBookingsTable from "../components/revenue/RevenueBookingsTable.vue";
import RevenueBreakdown from "../components/revenue/RevenueBreakdown.vue";
import { bookingRevenueExportUrl, fetchBookingRevenuePage, fetchBookingRevenueReport } from "../services/dashboardBookingRevenueApi";
import type { BookingRevenuePage, BookingRevenueReport, RevenueScope } from "../types/bookingRevenue";
import { formatEuroCents } from "../utils/money";
import { isIsoCalendarDate, normalizeRevenueDatePeriod } from "../utils/revenueDateRange";
import { normalizeRevenuePage, normalizeRevenueScope, relevantRevenuePages } from "../utils/revenueNavigation";

const route=useRoute(), router=useRouter();
const scopes:{value:RevenueScope;label:string;description:string}[]=[{value:"definitive",label:"Definitief",description:"Alleen definitieve boekingen"},{value:"option",label:"In optie",description:"Nog onzekere boekingen"},{value:"combined",label:"Prognose",description:"Definitief plus in optie"}];
const scope=ref<RevenueScope>(normalizeRevenueScope(route.query.revenueScope));
const page=ref(normalizeRevenuePage(route.query.page));
const startDate=ref(isIsoCalendarDate(route.query.start)?route.query.start:""); const endDate=ref(isIsoCalendarDate(route.query.end)?route.query.end:"");
const report=ref<BookingRevenueReport|null>(null); const bookings=ref<BookingRevenuePage|null>(null);
const loading=ref(false), listLoading=ref(false), error=ref(false), exportLoading=ref(false); const exportError=ref("");
let reportController:AbortController|undefined, listController:AbortController|undefined, reportSequence=0, listSequence=0;
const availableRange=computed(()=>report.value?.availableVisitDateRange??{min:null,max:null}); const hasAvailableDates=computed(()=>Boolean(availableRange.value.min&&availableRange.value.max));
const periodError=computed(()=>{if(!hasAvailableDates.value)return "";if(!startDate.value||!endDate.value)return "Kies een begin- en einddatum.";if(startDate.value<availableRange.value.min!||startDate.value>availableRange.value.max!||endDate.value<availableRange.value.min!||endDate.value>availableRange.value.max!)return "De periode valt buiten de beschikbare bezoekdatums.";return startDate.value>endDate.value?"De einddatum mag niet voor de begindatum liggen.":""});
const startMaximum=computed(()=>endDate.value&&availableRange.value.max?(endDate.value<availableRange.value.max?endDate.value:availableRange.value.max):availableRange.value.max??undefined);
const endMinimum=computed(()=>startDate.value&&availableRange.value.min?(startDate.value>availableRange.value.min?startDate.value:availableRange.value.min):availableRange.value.min??undefined);
const periodLabel=computed(()=>report.value?.period.startDate?`${dateLabel(report.value.period.startDate)} t/m ${dateLabel(report.value.period.endDate)}`:"Geen beschikbare bezoekperiode");
const combined=computed(()=>report.value?sumAmounts(report.value.definitiveRevenue,report.value.potentialRevenue):null);
const cards=computed(()=>{if(!report.value)return [];const r=report.value,c=r.counts;if(scope.value==="combined")return [["Definitieve omzet",formatEuroCents(r.definitiveRevenue.totalInclVatCents)],["Potentiële omzet (onzeker)",formatEuroCents(r.potentialRevenue.totalInclVatCents)],["Omzetprognose",formatEuroCents(combined.value!.totalInclVatCents)],["Definitieve boekingen",c.definitive],["Boekingen in optie",c.option],["Totaal boekingen",c.bookingsTotal],["Totaal leerlingen",c.studentsTotal],["Prijs ontbreekt",c.missingPrice]];const option=scope.value==="option",a=option?r.potentialRevenue:r.definitiveRevenue;return [[option?"Potentiële omzet incl. btw":"Definitieve omzet incl. btw",formatEuroCents(a.totalInclVatCents)],[option?"Potentiële omzet excl. btw":"Definitieve omzet excl. btw",formatEuroCents(a.totalExclVatCents)],[option?"Btw potentiële omzet":"Btw definitieve omzet",formatEuroCents(a.vatCents)],[option?"Boekingen in optie":"Definitieve boekingen",c.bookingsTotal],[option?"Leerlingen in optie":"Definitieve leerlingen",c.studentsTotal],["Prijs ontbreekt",c.missingPrice]]});
const pageNumbers=computed(()=>relevantRevenuePages(bookings.value?.pagination.currentPage??1,bookings.value?.pagination.totalPages??0));
function dateLabel(value:string){const[y,m,d]=value.split("-");return y&&m&&d?`${d}-${m}-${y}`:value}
function sumAmounts(a:any,b:any){return Object.fromEntries(Object.keys(a).map(key=>[key,a[key]+b[key]])) as typeof a}
async function syncUrl(replace=false){const query:Record<string,string>={revenueScope:scope.value,page:String(page.value)};if(startDate.value&&endDate.value){query.start=startDate.value;query.end=endDate.value}const same=Object.keys(query).length===Object.keys(route.query).length&&Object.entries(query).every(([k,v])=>route.query[k]===v);if(!same)await(replace?router.replace({query}):router.push({query}));}
async function loadReport(usePeriod=true){if(usePeriod&&periodError.value)return;reportController?.abort();const current=new AbortController();reportController=current;const request=++reportSequence;loading.value=true;error.value=false;try{const result=await fetchBookingRevenueReport(usePeriod?startDate.value||undefined:undefined,usePeriod?endDate.value||undefined:undefined,scope.value,current.signal);if(request!==reportSequence)return;report.value=result;scope.value=result.revenueScope;const normalized=normalizeRevenueDatePeriod(result.period.startDate,result.period.endDate,result.availableVisitDateRange);startDate.value=normalized?.startDate??"";endDate.value=normalized?.endDate??"";if(hasAvailableDates.value)await loadPage();else await syncUrl(true)}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError")&&request===reportSequence){report.value=null;error.value=true}}finally{if(request===reportSequence&&!current.signal.aborted)loading.value=false}}
async function loadPage(){if(!startDate.value||!endDate.value)return;listController?.abort();const current=new AbortController();listController=current;const request=++listSequence;listLoading.value=true;try{const result=await fetchBookingRevenuePage(startDate.value,endDate.value,scope.value,page.value,current.signal);if(request!==listSequence)return;bookings.value=result;page.value=result.pagination.currentPage;await syncUrl(true)}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError")&&request===listSequence)error.value=true}finally{if(request===listSequence&&!current.signal.aborted)listLoading.value=false}}
async function chooseScope(next:RevenueScope){if(next===scope.value)return;scope.value=next;page.value=1;await syncUrl();await loadReport()}
function moveScopeFocus(event:KeyboardEvent,index:number){let next=index;if(event.key==="ArrowRight"||event.key==="ArrowDown")next=(index+1)%scopes.length;else if(event.key==="ArrowLeft"||event.key==="ArrowUp")next=(index-1+scopes.length)%scopes.length;else if(event.key==="Home")next=0;else if(event.key==="End")next=scopes.length-1;else return;event.preventDefault();const selected=scopes[next];if(!selected)return;document.querySelectorAll<HTMLButtonElement>(".admin-revenue-scopes [role='tab']")[next]?.focus();void chooseScope(selected.value)}
async function applyPeriod(){page.value=1;await syncUrl();await loadReport()}
async function changePage(next:number){const p=bookings.value?.pagination;if(!p||next<1||next>p.totalPages||next===p.currentPage)return;page.value=next;await syncUrl();await loadPage();const reducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;document.querySelector(".admin-revenue-list")?.scrollIntoView({behavior:reducedMotion?"auto":"smooth",block:"start"})}
async function exportCsv(){if(exportLoading.value||!bookings.value?.pagination.totalItems)return;exportLoading.value=true;exportError.value="";try{const response=await fetch(bookingRevenueExportUrl(startDate.value,endDate.value,scope.value),{headers:{Accept:"text/csv"}});if(!response.ok)throw new Error();const blob=await response.blob();const disposition=response.headers.get("Content-Disposition")??"";const filename=/filename="([^"]+)"/.exec(disposition)?.[1]??"omzet.csv";const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url)}catch{exportError.value="De CSV-export kon niet worden gedownload. Probeer het opnieuw."}finally{exportLoading.value=false}}
onMounted(()=>void loadReport(Boolean(startDate.value&&endDate.value)));onBeforeUnmount(()=>{reportController?.abort();listController?.abort()});
</script>

<template><section class="admin-revenue-page" aria-labelledby="revenue-title"><header><p class="admin-eyebrow">Planning</p><h1 id="revenue-title">Omzet</h1><p>Betrouwbare omzet op basis van het nieuwste opgeslagen prijssnapshot per boeking.</p></header>
<div class="admin-revenue-scopes" role="tablist" aria-label="Omzetweergave"><button v-for="(item,index) in scopes" :key="item.value" type="button" role="tab" :aria-selected="scope===item.value" :aria-label="`${item.label}: ${item.description}`" :tabindex="scope===item.value?0:-1" @click="chooseScope(item.value)" @keydown="moveScopeFocus($event,index)">{{ item.label }}</button></div><p v-if="scope==='combined'" class="admin-revenue-notice">Definitieve omzet + potentiële omzet = omzetprognose. Het aandeel van boekingen in optie is nog onzeker.</p>
<form class="admin-revenue-filters" aria-label="Omzetperiode kiezen" @submit.prevent="applyPeriod"><AdminDateField v-model="startDate" name="revenue-start" label="Begindatum" :min="availableRange.min??undefined" :max="startMaximum" :disabled="!hasAvailableDates" :error="periodError?'Controleer de gekozen periode.':null" required/><AdminDateField v-model="endDate" name="revenue-end" label="Einddatum" :min="endMinimum" :max="availableRange.max??undefined" :disabled="!hasAvailableDates" :error="periodError||null" required/><AdminButton type="submit" :disabled="loading||!hasAvailableDates||Boolean(periodError)">Rapport tonen</AdminButton></form>
<p v-if="!loading&&report&&!hasAvailableDates" class="admin-revenue-state" role="status">Er zijn geen definitieve of in-optieboekingen met een geldige bezoekdatum.</p><template v-else><p class="admin-revenue-period"><strong>Actieve bezoekperiode:</strong> {{ periodLabel }}</p><div v-if="loading" class="admin-revenue-state" role="status">Omzetrapportage laden…</div><div v-else-if="error" class="admin-revenue-state" role="alert"><p>De omzetrapportage kon niet worden geladen.</p><AdminButton @click="loadReport()">Opnieuw proberen</AdminButton></div><template v-else-if="report"><div class="admin-revenue-cards"><article v-for="card in cards" :key="card[0]"><span>{{ card[0] }}</span><strong>{{ card[1] }}</strong></article></div><div v-if="scope==='combined'" class="admin-revenue-breakdowns"><RevenueBreakdown title="Definitieve omzet" description="Omzet uit definitieve boekingen." :amounts="report.definitiveRevenue"/><RevenueBreakdown title="Potentiële omzet" description="Boekingen in optie; dit is nog geen zekere omzet." :amounts="report.potentialRevenue"/></div>
<section class="admin-revenue-list" aria-labelledby="revenue-bookings-title"><div class="admin-revenue-list__header"><div><h2 id="revenue-bookings-title">Boekingen</h2><p>Alleen gegevens die nodig zijn voor de omzetcontrole.</p></div><AdminButton :disabled="exportLoading||!bookings?.pagination.totalItems" @click="exportCsv">{{ exportLoading?'CSV maken…':'Exporteer CSV' }}</AdminButton></div><p v-if="exportError" class="admin-revenue-export-error" role="alert">{{ exportError }}</p><p v-if="listLoading" class="admin-revenue-state" role="status">Boekingen laden…</p><p v-else-if="!bookings?.items.length" class="admin-revenue-state">Geen boekingen binnen deze selectie.</p><RevenueBookingsTable v-else :bookings="bookings.items"/><nav v-if="bookings&&bookings.pagination.totalPages>0" class="admin-revenue-pagination" aria-label="Boekingspagina's"><p>{{ bookings.pagination.from }}–{{ bookings.pagination.to }} van {{ bookings.pagination.totalItems }} boekingen</p><div><button type="button" :disabled="bookings.pagination.currentPage<=1" @click="changePage(bookings.pagination.currentPage-1)">Vorige</button><template v-for="(number,index) in pageNumbers" :key="number"><span v-if="index>0&&number-pageNumbers[index-1]!>1" class="admin-revenue-pagination__ellipsis" aria-hidden="true">…</span><button type="button" :aria-label="`Pagina ${number}`" :aria-current="number===bookings.pagination.currentPage?'page':undefined" @click="changePage(number)">{{ number }}</button></template><button type="button" :disabled="bookings.pagination.currentPage>=bookings.pagination.totalPages" @click="changePage(bookings.pagination.currentPage+1)">Volgende</button></div></nav></section></template></template></section></template>
