<script setup lang="ts">
import { computed,inject,ref } from "vue";
import AdminButton from "../form/AdminButton.vue";
import AdminDialog from "../feedback/AdminDialog.vue";
import { adminBootstrapKey } from "../../types/admin";
import type { BookingPriceState } from "../../types/bookingDetail";
import { acceptLegacyBookingPrice,LegacyPriceAcceptanceApiError } from "../../services/dashboardLegacyPriceAcceptanceApi";
const props=defineProps<{bookingId:number;price:BookingPriceState;status:string}>();
const emit=defineEmits<{completed:[message:string,refresh:boolean,conflict:boolean]}>();
const injectedBootstrap=inject(adminBootstrapKey);if(!injectedBootstrap)throw new Error("Admin bootstrapdata ontbreekt.");const bootstrap=injectedBootstrap;
const open=ref(false);const submitting=ref(false);const error=ref("");
const indication=computed(()=>props.price.currentIndication?{pricingVersion:props.price.currentIndication.pricingVersion,currencyCode:props.price.currentIndication.currencyCode,visitAmountInclVatCents:props.price.currentIndication.visit.amountInclVatCents,cateringAmountInclVatCents:props.price.currentIndication.foodAndDrink.amountInclVatCents,totalAmountInclVatCents:props.price.currentIndication.total.amountInclVatCents,totalAmountExclVatCents:props.price.currentIndication.total.amountExclVatCents,vatAmountCents:props.price.currentIndication.total.vatAmountCents,vatBasisPoints:props.price.currentIndication.vatBasisPoints}:null);
const shown=computed(()=>props.price.snapshot??indication.value);
const money=new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"});
function format(cents:number|null|undefined):string{return cents==null?"Onbekend":money.format(cents/100);}
async function accept():Promise<void>{submitting.value=true;error.value="";try{await acceptLegacyBookingPrice(props.bookingId,bootstrap.legacyPriceAcceptanceCsrfToken);open.value=false;emit("completed","De huidige prijs is vastgelegd. Kies daarna afzonderlijk Definitief bij Status beheren om de boeking te bevestigen.",true,false);}catch(caught){if(caught instanceof LegacyPriceAcceptanceApiError&&caught.code==="PRICE_SNAPSHOT_CONFLICT"){open.value=false;emit("completed","De prijs is ondertussen al vastgelegd. De actuele aanvraag wordt opnieuw geladen.",true,true);}else{error.value="De prijs kon niet worden vastgelegd. Er is niets gewijzigd; probeer het opnieuw.";}}finally{submitting.value=false;}}
</script>
<template><section class="admin-card admin-price-panel" aria-labelledby="booking-price-title"><h2 id="booking-price-title">Prijs</h2>
  <div v-if="price.calculationState==='complete'&&shown"><p><strong>Financieel vastgelegd</strong></p><dl class="admin-details"><dt>Prijsversie</dt><dd>{{shown.pricingVersion}}</dd><dt>Bezoek</dt><dd>{{format(shown.visitAmountInclVatCents)}}</dd><dt>Eten en drinken</dt><dd>{{format(shown.cateringAmountInclVatCents)}}</dd><dt>Btw</dt><dd>{{format(shown.vatAmountCents)}}</dd><dt>Totaal inclusief btw</dt><dd>{{format(shown.totalAmountInclVatCents)}}</dd></dl></div>
  <div v-else-if="price.calculationState==='stale'"><p role="alert"><strong>Prijsgegevens komen niet overeen met de actuele boekingsgegevens.</strong></p><p>Bevestig deze boeking niet voordat de financiële vastlegging is hersteld.</p></div>
  <div v-else><p role="status"><strong>Historische prijs niet beschikbaar</strong></p><template v-if="shown"><p>Actuele prijsindicatie – nog niet financieel vastgelegd</p><dl class="admin-details"><dt>Prijsversie</dt><dd>{{shown.pricingVersion}}</dd><dt>Bezoek</dt><dd>{{format(shown.visitAmountInclVatCents)}}</dd><dt>Eten en drinken</dt><dd>{{format(shown.cateringAmountInclVatCents)}}</dd><dt>Totaal</dt><dd>{{format(shown.totalAmountInclVatCents)}}</dd></dl><AdminButton v-if="status==='In optie'" @click="open=true">Huidige prijs vastleggen</AdminButton><p v-else>Voor reeds definitieve of afgewezen boekingen is in deze flow geen financiële vastlegging toegestaan.</p></template></div>
  <AdminDialog :open="open" title="Huidige prijs vastleggen" :close-disabled="submitting" @close="open=false"><p>Deze bestaande boeking heeft nog geen opgeslagen prijs. Je staat op het punt de huidige prijsindicatie als nieuwe financiële afspraak vast te leggen. Dit herstelt niet de oorspronkelijke historische prijs.</p><p>Dit wijzigt de boekingsstatus nog niet. Na succesvolle vastlegging bevestig je de boeking afzonderlijk bij Status beheren.</p><dl v-if="shown" class="admin-details"><dt>Prijsversie</dt><dd>{{shown.pricingVersion}}</dd><dt>Bezoek</dt><dd>{{format(shown.visitAmountInclVatCents)}}</dd><dt>Eten en drinken</dt><dd>{{format(shown.cateringAmountInclVatCents)}}</dd><dt>Totaal</dt><dd>{{format(shown.totalAmountInclVatCents)}}</dd></dl><p v-if="error" role="alert">{{error}}</p><template #footer><AdminButton variant="secondary" :disabled="submitting" @click="open=false">Annuleren</AdminButton><AdminButton :loading="submitting" :disabled="submitting" @click="accept">Prijs expliciet vastleggen</AdminButton></template></AdminDialog>
</section></template>
