<script setup lang="ts">
import { computed } from "vue";
import AdminButton from "../form/AdminButton.vue";
import AdminDialog from "../feedback/AdminDialog.vue";
import type { BookingValidationIssue } from "../../types/bookingStatus";
const props=defineProps<{open:boolean;issues:BookingValidationIssue[];submitting:boolean;reasons:Record<string,string>}>();
const emit=defineEmits<{close:[];confirm:[];"update:reason":[code:string,value:string]}>();
const valid=computed(()=>props.issues.length>0&&props.issues.every(i=>{const n=(props.reasons[i.code]??"").trim().length;return n>=15&&n<=500;}));
function label(key:string):string{return ({confirmedStudents:"Al definitieve leerlingen",confirmedStudentsExcludingBooking:"Definitieve leerlingen zonder deze aanvraag",previousBookingStudents:"Vorig aantal leerlingen",proposedBookingStudents:"Nieuw aantal leerlingen",bookingStudents:"Leerlingen in deze aanvraag",projectedStudents:"Totaal na wijziging",maximumStudents:"Maximum leerlingen",confirmedSchools:"Al definitieve scholen",confirmedSchoolsExcludingBooking:"Definitieve scholen zonder deze aanvraag",projectedSchools:"Totaal scholen",maximumSchools:"Maximum scholen",supervisorCount:"Opgegeven begeleiders",minimumSupervisors:"Minimaal vereist",studentCount:"Leerlingen"} as Record<string,string>)[key]??key;}
</script>
<template><AdminDialog :open="open" title="Bewust afwijken van boekingsregels" description="Je staat op het punt bewust af te wijken van een boekingsregel. Deze keuze en je reden worden vastgelegd in het auditlog." :close-on-backdrop="!submitting" :close-on-escape="!submitting" @close="emit('close')"><div class="admin-override-dialog__issues"><section v-for="issue in issues" :key="issue.code" class="admin-override-dialog__issue"><h3>{{ issue.title }}</h3><p>{{ issue.description }}</p><dl v-if="Object.keys(issue.metadata).length" class="admin-override-dialog__metadata"><template v-for="(value,key) in issue.metadata" :key="key"><dt>{{ label(String(key)) }}</dt><dd>{{ typeof value==='boolean'?(value?'Ja':'Nee'):value }}</dd></template></dl><label :for="`override-reason-${issue.code}`">Reden voor deze afwijking</label><textarea :id="`override-reason-${issue.code}`" :value="reasons[issue.code]??''" rows="4" maxlength="500" :disabled="submitting" required @input="emit('update:reason',issue.code,($event.target as HTMLTextAreaElement).value)"/><small>Minimaal 15 en maximaal 500 tekens.</small></section></div><template #footer><AdminButton variant="secondary" :disabled="submitting" @click="emit('close')">Annuleren</AdminButton><AdminButton :disabled="!valid||submitting" :loading="submitting" @click="emit('confirm')">Toch doorgaan</AdminButton></template></AdminDialog></template>
