<?php

declare(strict_types=1);

require dirname(__DIR__,2).'/vendor/autoload.php';

use GeoFort\Booking\Cjp\{BookingCjpChangeCode,BookingCjpChangeCommand,BookingCjpDetails};
use GeoFort\Services\Booking\Cjp\BookingCjpChangeServiceFactory;

$env=[];foreach(['HOST','PORT','NAME','USER']as$key){$value=getenv('STATUS_TEST_DB_'.$key);if($value===false){fwrite(STDERR,"FAIL: STATUS_TEST_DB_{$key} ontbreekt.\n");exit(2);}$env[$key]=(string)$value;}
if(getenv('STATUS_TEST_DB_CONFIRM')!=='YES_DISPOSABLE'||preg_match('/(test|tmp|scratch|disposable)/i',$env['NAME'])!==1||strtolower((string)getenv('APP_ENV'))==='production'){fwrite(STDERR,"FAIL: integratietest weigert niet-aantoonbaar wegwerpbare database.\n");exit(2);}
$pdo=new PDO(sprintf('mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4',$env['HOST'],$env['PORT'],$env['NAME']),$env['USER'],(string)(getenv('STATUS_TEST_DB_PASSWORD')?:''),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$tables=['booking_change_history','booking_status_history','aanvraag_onderwijs_selecties','aanvragen','admin_users'];$cleanup=static function()use($pdo,$tables):void{$pdo->exec('SET FOREIGN_KEY_CHECKS=0');try{foreach($tables as$table)$pdo->exec("DROP TABLE IF EXISTS {$table}");}finally{$pdo->exec('SET FOREIGN_KEY_CHECKS=1');}};$cleanup();$exit=0;
try{
$pdo->exec("CREATE TABLE aanvragen(id INT AUTO_INCREMENT PRIMARY KEY,status VARCHAR(20) NOT NULL,schoolnaam VARCHAR(255) NOT NULL,land VARCHAR(32) NOT NULL,adres VARCHAR(255) NOT NULL,postcode VARCHAR(16) NOT NULL,plaats VARCHAR(120) NOT NULL,school_telefoonnummer VARCHAR(25) NOT NULL,contactpersoon_telefoonnummer VARCHAR(25) NOT NULL,contactpersoon_voornaam VARCHAR(255) NOT NULL,contactpersoon_achternaam VARCHAR(255) NOT NULL,email VARCHAR(255) NOT NULL,bezoekdatum DATE NOT NULL,hoe_kent_u_geofort VARCHAR(120),opmerkingen TEXT,cjpPasGebruik VARCHAR(3) NOT NULL,cjpContactpersoonNaam VARCHAR(80),cjpPasnummer VARCHAR(9),onderwijs_sector VARCHAR(40) NOT NULL,programma VARCHAR(20) NOT NULL,keuzemodule_key VARCHAR(120),aantal_leerlingen INT,aantal_begeleiders INT,remise_break INT DEFAULT 0,kazerne_break INT DEFAULT 0,fortgracht_break INT DEFAULT 0,glas_limonade INT DEFAULT 0,waterijsje INT DEFAULT 0,remise_lunch INT DEFAULT 0,eigen_picknick TINYINT DEFAULT 1,voorwaarden_akkoord TINYINT DEFAULT 1,voorwaarden_akkoord_op DATETIME,source_system VARCHAR(80),source_record_id BIGINT,source_record_checksum CHAR(64),source_import_run_id BIGINT,price_total DECIMAL(10,2) DEFAULT 123.45) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE admin_users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190),name VARCHAR(120),role VARCHAR(50),password_hash VARCHAR(255)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE aanvraag_onderwijs_selecties(id INT AUTO_INCREMENT PRIMARY KEY,aanvraag_id INT NOT NULL,sector_key VARCHAR(40),level_key VARCHAR(80),group_key VARCHAR(80),level_position INT,group_position INT) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE booking_status_history(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,booking_id INT)");
$pdo->exec((string)file_get_contents(dirname(__DIR__,2).'/database/sql/2026-07-22_create_booking_change_history.sql'));
$pdo->exec("INSERT INTO admin_users(email,name,role,password_hash)VALUES('cjp@example.test','Planner','admin','x')");$admin=(int)$pdo->lastInsertId();
$insert=static function()use($pdo):int{$pdo->exec("INSERT INTO aanvragen(status,schoolnaam,land,adres,postcode,plaats,school_telefoonnummer,contactpersoon_telefoonnummer,contactpersoon_voornaam,contactpersoon_achternaam,email,bezoekdatum,cjpPasGebruik,onderwijs_sector,programma,keuzemodule_key,aantal_leerlingen,aantal_begeleiders)VALUES('Definitief','School','Nederland','Dijk 1','1234 AB','Plaats','010 123 4567','06 12345678','Jan','Jansen','jan@example.nl','2026-09-01','nee','primairOnderwijs','dag','Earth-Watch',40,5)");return(int)$pdo->lastInsertId();};
$change=static fn(int$id,BookingCjpDetails$expected,BookingCjpDetails$proposed)=>(new BookingCjpChangeServiceFactory($pdo))->create()->change(new BookingCjpChangeCommand($id,$expected,$proposed,$admin));
$assert=static function(bool$condition,string$message):void{if(!$condition)throw new RuntimeException($message);};$old=new BookingCjpDetails('nee',null,null);$new=new BookingCjpDetails('ja',' Jan  de Vries ','1234 5678');
$id=$insert();$before=$pdo->query("SELECT status,programma,bezoekdatum,price_total FROM aanvragen WHERE id={$id}")->fetch();$result=$change($id,$old,$new);$after=$pdo->query("SELECT status,programma,bezoekdatum,price_total,cjpPasGebruik,cjpContactpersoonNaam,cjpPasnummer FROM aanvragen WHERE id={$id}")->fetch();
$assert($result->code===BookingCjpChangeCode::Success&&$after['cjpContactpersoonNaam']==='Jan de Vries'&&$after['cjpPasnummer']==='12345678','Update of normalisatie faalt.');foreach($before as$key=>$value)$assert($after[$key]===$value,"Niet-CJP-veld {$key} wijzigde.");
$audit=$pdo->query("SELECT change_type,changed_fields_json FROM booking_change_history WHERE booking_id={$id}")->fetch();$fields=json_decode($audit['changed_fields_json'],true,512,JSON_THROW_ON_ERROR);$assert($audit['change_type']==='cjp_details_changed'&&array_keys($fields)===['cjpPasGebruik','cjpContactpersoonNaam','cjpPasnummer'],'Auditdiff is onjuist.');
$remove=$change($id,$result->current,new BookingCjpDetails('nee','Aangepaste client','87654321'));$removed=$pdo->query("SELECT status,programma,bezoekdatum,price_total,cjpPasGebruik,cjpContactpersoonNaam,cjpPasnummer FROM aanvragen WHERE id={$id}")->fetch();$assert($remove->code===BookingCjpChangeCode::Success&&$removed['cjpPasGebruik']==='nee'&&$removed['cjpContactpersoonNaam']===null&&$removed['cjpPasnummer']===null,'Ja naar nee verwijdert vervolgwaarden niet autoritatief.');foreach($before as$key=>$value)$assert($removed[$key]===$value,"Ja-naar-nee wijzigde niet-CJP-veld {$key}.");
$audits=$pdo->query("SELECT change_type,changed_fields_json FROM booking_change_history WHERE booking_id={$id} ORDER BY id")->fetchAll();$removedFields=json_decode($audits[1]['changed_fields_json'],true,512,JSON_THROW_ON_ERROR);$assert(count($audits)===2&&$audits[1]['change_type']==='cjp_details_changed'&&$removedFields===['cjpPasGebruik'=>['before'=>'ja','after'=>'nee'],'cjpContactpersoonNaam'=>['before'=>'Jan de Vries','after'=>null],'cjpPasnummer'=>['before'=>'12345678','after'=>null]],'Ja-naar-nee audit bevat niet alle verwijderde waarden.');
$noop=$change($id,new BookingCjpDetails('nee',null,null),new BookingCjpDetails('nee','Verborgen','12345678'));$assert($noop->code===BookingCjpChangeCode::NoChange&&(int)$pdo->query("SELECT COUNT(*) FROM booking_change_history WHERE booking_id={$id}")->fetchColumn()===2,'Normalisatie vóór no-op faalt of no-op schrijft.');
$assert($change($id,$old,$new)->code===BookingCjpChangeCode::Success,'Actuele nee-state wordt ten onrechte als conflict behandeld.');$assert($change($id,$old,$new)->code===BookingCjpChangeCode::Conflict,'Conflict schrijft of wordt niet herkend.');$invalid=new BookingCjpDetails('ja','',null);$current=new BookingCjpDetails('ja','Jan de Vries','12345678');$assert($change($id,$current,$invalid)->code===BookingCjpChangeCode::InvalidDetails,'Validatiefout muteert.');
$assert((int)$pdo->query('SELECT COUNT(*) FROM booking_status_history')->fetchColumn()===0,'Statushistory geschreven.');
$pdo->exec('DROP TABLE booking_change_history');$rollback=$insert();$assert($change($rollback,$old,$new)->code===BookingCjpChangeCode::DatabaseError&&$pdo->query("SELECT cjpPasGebruik FROM aanvragen WHERE id={$rollback}")->fetchColumn()==='nee','Auditfout rolt update niet terug.');
echo "BookingCjpChangeMariaDbIntegrationTest OK\n";
}catch(Throwable$exception){fwrite(STDERR,'FAIL: '.$exception->getMessage()."\n");$exit=1;}finally{$cleanup();}exit($exit);
