<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/vendor/autoload.php';

use GeoFort\Booking\ProgramConfiguration\{BookingProgramConfigurationCode,BookingProgramConfigurationCommand,BookingProgramConfigurationSnapshot};
use GeoFort\Booking\Rules\BookingRuleOverrideRequest;
use GeoFort\Booking\Stored\{StoredBookingAssembler};
use GeoFort\Services\Booking\Data\EducationSelectionData;
use GeoFort\Services\Booking\ProgramConfiguration\BookingProgramConfigurationServiceFactory;
use GeoFort\Services\Sql\StoredBookingSqlRepository;

if(($_ENV['STATUS_TEST_DB_CONFIRM']??getenv('STATUS_TEST_DB_CONFIRM'))!=='YES_DISPOSABLE')throw new RuntimeException('Disposable databasebevestiging ontbreekt.');
$env=static fn(string $key,string $default=''):string=>(string)($_ENV[$key]??getenv($key)?:$default);$database=$env('STATUS_TEST_DB_NAME');if($database!=='geofort_status_mutation_test')throw new RuntimeException('Onverwachte testdatabase.');
$pdo=new PDO('mysql:host='.$env('STATUS_TEST_DB_HOST','127.0.0.1').';port='.$env('STATUS_TEST_DB_PORT','3306').';dbname='.$database.';charset=utf8mb4',$env('STATUS_TEST_DB_USER','root'),$env('STATUS_TEST_DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$assert=static function(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);};$ids=[];$triggers=[];
$insert=$pdo->prepare("INSERT INTO aanvragen(status,schoolnaam,land,adres,postcode,plaats,school_telefoonnummer,contactpersoon_telefoonnummer,contactpersoon_voornaam,contactpersoon_achternaam,email,bezoekdatum,cjpPasGebruik,onderwijs_sector,programma,keuzemodule_key,aantal_leerlingen,aantal_begeleiders,remise_break,voorwaarden_akkoord) VALUES(:status,'Aggregaattest','Nederland','Dijk 1','1234 AB','Plaats','1','2','Jan','Jansen','aggregate@example.test',:date,'nee','primairOnderwijs',:program,:module,:students,5,3,1)");
$selection=$pdo->prepare("INSERT INTO aanvraag_onderwijs_selecties(aanvraag_id,sector_key,sector_label,level_key,level_label,level_position,group_key,group_label,group_position) VALUES(:id,'primairOnderwijs','Primair onderwijs','regulier','Regulier basisonderwijs',1,'groep7','Groep 7',1)");
$make=static function(string $status,string $date,string $program='dag',?string $module='Earth-Watch',int $students=40)use($insert,$selection,$pdo,&$ids):int{$insert->execute([':status'=>$status,':date'=>$date,':program'=>$program,':module'=>$module,':students'=>$students]);$id=(int)$pdo->lastInsertId();$ids[]=$id;$selection->execute([':id'=>$id]);return$id;};
$repository=new StoredBookingSqlRepository($pdo,new StoredBookingAssembler());$service=(new BookingProgramConfigurationServiceFactory($pdo))->create();
$command=static function(int $id,string $program,int $students,?string $module,array $overrides=[])use($repository):BookingProgramConfigurationCommand{$booking=$repository->findById($id);$expected=BookingProgramConfigurationSnapshot::fromBooking($booking);$proposed=new BookingProgramConfigurationSnapshot($expected->status,$expected->visitDate,$program,$students,new EducationSelectionData('primairOnderwijs',['regulier'],['regulier'=>['groep7']]),$module);return new BookingProgramConfigurationCommand($id,$expected,$proposed,1,$overrides);};
try{
 foreach(['In optie','Definitief','Afgewezen'] as $status){$id=$make($status,'2027-02-08');$required=$service->change($command($id,'ochtend',40,null));$assert($required->code===BookingProgramConfigurationCode::OverrideRequired,'Maandag Ochtend vereist geen override.');$success=$service->change($command($id,'ochtend',40,null,[new BookingRuleOverrideRequest('PROGRAM_WEEKDAY_MISMATCH','Planner wijkt bewust af van de normale weekdag.')]));$row=$pdo->query("SELECT status,bezoekdatum,programma,aantal_leerlingen,remise_break FROM aanvragen WHERE id={$id}")->fetch();$audit=$pdo->query("SELECT id,change_type,changed_fields_json FROM booking_change_history WHERE booking_id={$id}")->fetch();$override=$pdo->query("SELECT status_history_id,booking_change_history_id,rule_code FROM booking_rule_overrides WHERE booking_id={$id}")->fetch();$assert($success->code===BookingProgramConfigurationCode::Success&&$row['status']===$status&&$row['bezoekdatum']==='2027-02-08'&&$row['programma']==='ochtend'&&(int)$row['remise_break']===3,'Overrideflow wijzigt onbedoelde velden.');$assert($audit['change_type']==='program_configuration_changed'&&$override['status_history_id']===null&&(int)$override['booking_change_history_id']===(int)$audit['id']&&$override['rule_code']==='PROGRAM_WEEKDAY_MISMATCH','Aggregateaudit of override-XOR faalt.');}
 $wednesday=$make('In optie','2027-02-10');$assert($service->change($command($wednesday,'ochtend',40,null))->code===BookingProgramConfigurationCode::Success,'Woensdag Ochtend faalt zonder override.');
 $day=$make('In optie','2027-02-10','ochtend',null,40);$result=$service->change($command($day,'dag',80,'Earth-Watch'));$fields=json_decode((string)$pdo->query("SELECT changed_fields_json FROM booking_change_history WHERE booking_id={$day}")->fetchColumn(),true,512,JSON_THROW_ON_ERROR);$fieldKeys=array_keys($fields);sort($fieldKeys);$assert($result->code===BookingProgramConfigurationCode::Success&&$fieldKeys===['aantal_leerlingen','keuzemodule_key','programma'],'Audit bevat niet alleen werkelijk gewijzigde velden: '.implode(',',$fieldKeys));
 $educationOnly=$make('In optie','2027-02-10');$educationExpected=BookingProgramConfigurationSnapshot::fromBooking($repository->findById($educationOnly));$educationProposed=new BookingProgramConfigurationSnapshot($educationExpected->status,$educationExpected->visitDate,$educationExpected->program,$educationExpected->studentCount,new EducationSelectionData('primairOnderwijs',['regulier'],['regulier'=>['groep8']]),$educationExpected->choiceModule);$educationResult=$service->change(new BookingProgramConfigurationCommand($educationOnly,$educationExpected,$educationProposed,1));$assert($educationResult->code===BookingProgramConfigurationCode::Success&&(string)$pdo->query("SELECT group_key FROM aanvraag_onderwijs_selecties WHERE aanvraag_id={$educationOnly}")->fetchColumn()==='groep8','Onderwijsselectie-only mutatie wordt niet atomair opgeslagen.');
 foreach([[null,'MISSING_CHOICE_MODULE'],['Onbekend','INVALID_CHOICE_MODULE']] as [$invalidModule,$issueCode]){$invalidId=$make('In optie','2027-02-10');$invalidResult=$service->change($command($invalidId,'dag',80,$invalidModule));$assert($invalidResult->code===BookingProgramConfigurationCode::InvalidConfiguration&&($invalidResult->issues[0]->code??'')===$issueCode&&(string)$pdo->query("SELECT keuzemodule_key FROM aanvragen WHERE id={$invalidId}")->fetchColumn()==='Earth-Watch'&&(int)$pdo->query("SELECT COUNT(*) FROM booking_change_history WHERE booking_id={$invalidId}")->fetchColumn()===0,"{$issueCode} schrijft data of audit.");}
 $tooManyId=$make('In optie','2027-02-10');$tooManyExpected=BookingProgramConfigurationSnapshot::fromBooking($repository->findById($tooManyId));$tooManyProposed=new BookingProgramConfigurationSnapshot($tooManyExpected->status,$tooManyExpected->visitDate,'dag',80,new EducationSelectionData('primairOnderwijs',['regulier'],['regulier'=>['groep5','groep6','groep7','groep8']]),'Earth-Watch');$tooManyResult=$service->change(new BookingProgramConfigurationCommand($tooManyId,$tooManyExpected,$tooManyProposed,1));$assert(($tooManyResult->issues[0]->code??'')==='GROUP_SELECTION_LIMIT_EXCEEDED'&&(string)$pdo->query("SELECT COUNT(*) FROM aanvraag_onderwijs_selecties WHERE aanvraag_id={$tooManyId}")->fetchColumn()==='1'&&(int)$pdo->query("SELECT COUNT(*) FROM booking_change_history WHERE booking_id={$tooManyId}")->fetchColumn()===0,'Te veel groepen schrijft data of audit.');
 $conflictId=$make('In optie','2027-02-10');$stale=$command($conflictId,'ochtend',40,null);$pdo->exec("UPDATE aanvragen SET aantal_leerlingen=41 WHERE id={$conflictId}");$assert($service->change($stale)->code===BookingProgramConfigurationCode::Conflict,'Volledige expected snapshot detecteert leerlingconflict niet.');
 $rollbackId=$make('In optie','2027-02-10');$pdo->exec("CREATE TRIGGER fail_program_configuration_history BEFORE INSERT ON booking_change_history FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced audit failure'");$triggers[]='fail_program_configuration_history';$failed=$service->change($command($rollbackId,'ochtend',40,null));$pdo->exec('DROP TRIGGER fail_program_configuration_history');array_pop($triggers);$assert($failed->code===BookingProgramConfigurationCode::DatabaseError&&(string)$pdo->query("SELECT programma FROM aanvragen WHERE id={$rollbackId}")->fetchColumn()==='dag','Auditfout rolt aggregate niet terug.');
 fwrite(STDOUT,"OK: programmaconfiguratie MariaDB-integratie geslaagd.\n");
}finally{foreach($triggers as $trigger)$pdo->exec("DROP TRIGGER IF EXISTS {$trigger}");if($ids!==[]){$list=implode(',',array_map('intval',$ids));$pdo->exec("DELETE FROM booking_rule_overrides WHERE booking_id IN ({$list})");$pdo->exec("DELETE FROM booking_change_history WHERE booking_id IN ({$list})");$pdo->exec("DELETE FROM aanvraag_onderwijs_selecties WHERE aanvraag_id IN ({$list})");$pdo->exec("DELETE FROM aanvragen WHERE id IN ({$list})");}}
