<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/vendor/autoload.php';require __DIR__.'/Support/DisposableBookingMariaDb.php';

use GeoFort\Booking\Stored\StoredBookingAssembler;
use GeoFort\Services\Booking\Pricing\Backfill\BookingPriceSnapshotBackfillService;
use GeoFort\Services\Booking\Pricing\BookingPriceCalculator;
use GeoFort\Services\Booking\Pricing\BookingPriceSnapshot;
use GeoFort\Services\Booking\Pricing\BookingPriceSnapshotService;
use GeoFort\Services\Booking\Pricing\StoredBookingPricingInputFactory;
use GeoFort\Services\Sql\BookingPriceBackfillSqlRepository;
use GeoFort\Services\Sql\BookingPriceSnapshotSqlRepository;
use GeoFort\Services\Sql\StoredBookingSqlRepository;

$assert=static function(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);};$db=DisposableBookingMariaDb::create('price_backfill');
try{$pdo=$db->pdo;$insert=$pdo->prepare("INSERT INTO aanvragen(status,schoolnaam,land,adres,postcode,plaats,school_telefoonnummer,contactpersoon_telefoonnummer,contactpersoon_voornaam,contactpersoon_achternaam,email,bezoekdatum,cjpPasGebruik,onderwijs_sector,programma,aantal_leerlingen,aantal_begeleiders,eigen_picknick,voorwaarden_akkoord,source_system,source_record_id,source_record_checksum)VALUES(:status,:school,'Nederland','Dijk 1','1234 AB','Plaats','1','2','Voor','Naam',:email,'2026-09-01','nee','primairOnderwijs','dag',:students,2,1,1,:source,:record,:checksum)");
for($i=1;$i<=140;$i++){$sourceRecordId=$i===140?155:$i;$insert->execute([':status'=>['In optie','Definitief','Afgewezen'][$i%3],':school'=>"School {$i}",':email'=>"school{$i}@example.test",':students'=>$i===139?null:10,':source'=>'legacy-school-db',':record'=>$sourceRecordId,':checksum'=>hash('sha256',(string)$sourceRecordId)]);$id=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO aanvraag_onderwijs_selecties(aanvraag_id,sector_key,level_key,group_key,level_position,group_position)VALUES(:id,'primairOnderwijs','regulier','groep5',1,1)")->execute([':id'=>$id]);}
$stored=new StoredBookingSqlRepository($pdo,new StoredBookingAssembler());$calculator=new BookingPriceCalculator();$snapshots=new BookingPriceSnapshotService(new BookingPriceSnapshotSqlRepository($pdo),$calculator);$service=new BookingPriceSnapshotBackfillService($pdo,new BookingPriceBackfillSqlRepository($pdo),$stored,new StoredBookingPricingInputFactory(),$calculator,$snapshots);
$firstBooking=$stored->findById(1)??throw new RuntimeException('Fixture ontbreekt.');$pdo->beginTransaction();$snapshots->appendUsingActiveVersion(1,GeoFort\Services\Booking\Pricing\BookingPricingInput::fromStoredBooking($firstBooking),BookingPriceSnapshot::REASON_LEGACY_ACCEPTANCE);$pdo->commit();
$before=(int)$pdo->query('SELECT COUNT(*) FROM booking_price_snapshots')->fetchColumn();$dry=$service->analyze();$after=(int)$pdo->query('SELECT COUNT(*) FROM booking_price_snapshots')->fetchColumn();
$assert($before===1&&$after===1,'Dry-runanalyse heeft snapshots gewijzigd.');$assert($dry->reconciliationMatches(140,140,0,1,155)&&$dry->withSnapshot===1&&$dry->withoutSnapshot===139&&$dry->calculable===138&&$dry->notCalculable===1,'Dry-runtotalen of 140+0-reconciliatie onjuist.');$assert($dry->legacyWithSourceRecordId===140&&$dry->uniqueLegacySourceRecordIds===140&&$dry->legacyWithoutSourceRecordId===0,'Legacy source_record_id-integriteit onjuist.');$assert($dry->exceptions[0]['bookingId']===139&&$dry->exceptions[0]['sourceRecordId']===139&&$dry->exceptions[0]['invalidFields']===['aantal_leerlingen'],'Ongeldige boeking wordt niet specifiek gerapporteerd.');$lastCandidate=array_values(array_filter($dry->candidates,static fn(array $row):bool=>$row['bookingId']===140))[0];$assert($lastCandidate['sourceRecordId']===155&&$lastCandidate['sourceCategory']==='legacy','Lokale booking-ID wordt onjuist als bron-ID gebruikt.');
$executed=$service->execute();$assert($executed->added===138&&(int)$pdo->query('SELECT COUNT(*) FROM booking_price_snapshots')->fetchColumn()===139,'Execute heeft niet exact berekenbare snapshots toegevoegd.');
$second=$service->execute();$assert($second->added===0&&(int)$pdo->query('SELECT COUNT(*) FROM booking_price_snapshots')->fetchColumn()===139,'Tweede execute-run is niet idempotent.');
$invalid=(int)$pdo->query("SELECT COUNT(*) FROM booking_price_snapshots WHERE calculation_state<>'complete' OR canonical_input_json IS NULL OR input_checksum NOT REGEXP '^[a-f0-9]{64}$'")->fetchColumn();$assert($invalid===0,'Snapshotcontract/checksum/state is beschadigd.');
$legacyReason=(string)$pdo->query('SELECT snapshot_reason FROM booking_price_snapshots WHERE booking_id=140')->fetchColumn();$assert($legacyReason===BookingPriceSnapshot::REASON_LEGACY_ACCEPTANCE,'Legacy snapshotreden onjuist.');
$insert->execute([':status'=>'In optie',':school'=>'Native',':email'=>'native@example.test',':students'=>10,':source'=>null,':record'=>null,':checksum'=>null]);$nativeId=(int)$pdo->lastInsertId();$nativeAnalysis=$service->analyze();$nativeRows=array_values(array_filter($nativeAnalysis->candidates,static fn(array $row):bool=>$row['bookingId']===$nativeId));$assert($nativeAnalysis->nativeBookings===1&&count($nativeRows)===1&&$nativeRows[0]['sourceCategory']==='native'&&$nativeRows[0]['sourceRecordId']===null&&$nativeRows[0]['snapshotReason']===BookingPriceSnapshot::REASON_SUBMISSION,'Echte native boeking wordt niet veilig onderscheiden.');$beforeMismatch=(int)$pdo->query('SELECT COUNT(*) FROM booking_price_snapshots')->fetchColumn();try{$service->execute();throw new RuntimeException('Afwijkende reconciliatie werd geaccepteerd.');}catch(RuntimeException $exception){$assert($exception->getMessage()==='BACKFILL_RECONCILIATION_MISMATCH','Onverwachte reconciliatiefout.');}$assert(!$pdo->inTransaction()&&(int)$pdo->query('SELECT COUNT(*) FROM booking_price_snapshots')->fetchColumn()===$beforeMismatch,'Native reconciliatieafwijking is niet volledig teruggedraaid.');
echo "Booking price snapshot backfill MariaDB integration tests passed.\n";
}finally{$db->drop();}
