<?php
declare(strict_types=1);
$root=dirname(__DIR__,2);$view=(string)file_get_contents($root.'/resources/js/admin/views/DashboardBookingRevenueView.vue');$table=(string)file_get_contents($root.'/resources/js/admin/components/revenue/RevenueBookingsTable.vue');$service=(string)file_get_contents($root.'/resources/js/admin/services/dashboardBookingRevenueApi.ts');$types=(string)file_get_contents($root.'/resources/js/admin/types/bookingRevenue.ts');$money=(string)file_get_contents($root.'/resources/js/admin/utils/money.ts');$router=(string)file_get_contents($root.'/resources/js/admin/router/index.ts');$navigation=(string)file_get_contents($root.'/resources/js/admin/components/layout/DashboardNavigation.vue');
$assert=static function(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);};
$assert(str_contains($router,'path: "/omzet"')&&str_contains($navigation,'to="/omzet"'),'Omzetroute of navigatie ontbreekt.');
$assert(strpos($navigation,'Agenda')<strpos($navigation,'Export')&&strpos($navigation,'Export')<strpos($navigation,'Omzet'),'Navigatievolgorde onjuist.');
$range=(string)file_get_contents($root.'/resources/js/admin/utils/revenueDateRange.ts');
$assert(str_contains($service,'revenue.php')&&str_contains($service,'revenue-bookings.php')&&str_contains($service,'revenue-export.php'),'Getypepte omzet-API ontbreekt.');
foreach(['definitiveRevenue','potentialRevenue','BookingRevenuePage','RevenuePagination','amounts: RevenueAmounts | null'] as $contract)$assert(str_contains($types,$contract),"Responsecontract mist {$contract}.");
$assert(str_contains($types,'availableVisitDateRange: { min: string | null; max: string | null }'),'Datumgrenzen ontbreken in het frontendcontract.');
$assert(str_contains($view,'Omzetrapportage laden')&&str_contains($view,'role="alert"')&&str_contains($view,'Geen boekingen binnen deze selectie'),'Loading-, fout- of lege staat ontbreekt.');
$assert(str_contains($view,'report.value.definitiveRevenue')&&!str_contains($view,'reduce('),'Frontend herberekent omzet of gebruikt backendtotalen niet.');
$assert(substr_count($view,':min="')>=2&&substr_count($view,':max="')>=2&&str_contains($view,':disabled="!hasAvailableDates"'),'Beide datumvelden ontvangen niet dezelfde globale min/max of lege-state-disable.');
$assert(str_contains($view,'router.replace')&&str_contains($view,'request!==reportSequence')&&str_contains($view,'reportController?.abort()')&&str_contains($view,'listController?.abort()'),'URL-normalisatie of stale-requestbescherming ontbreekt.');
$assert(str_contains($view,'Er zijn geen definitieve of in-optieboekingen met een geldige bezoekdatum.'),'Nederlandse lege staat ontbreekt.');
$assert(str_contains($range,'startDate > range.max || endDate < range.min')&&str_contains($range,'normalizedStart <= normalizedEnd'),'Veilige datumperiodenormalisatie ontbreekt.');
$assert(str_contains((string)file_get_contents($root.'/scripts/tests/bookingRevenueDateRangeInteractionTest.mjs'),'"2027-03-01", "2026-10-01"'),'Expliciete frontendtest voor een omgekeerde periode ontbreekt.');
$assert(str_contains($money,'cents / 100')&&str_contains($money,'currency: "EUR"'),'Centrale centenformatter ontbreekt.');
$assert(str_contains($table,'v-if="booking.amounts"')&&str_contains($table,'Prijs ontbreekt')&&str_contains($table,'colspan="3"'),'Ontbrekende prijs wordt misleidend getoond.');
$assert(str_contains($view,'role="tablist"')&&str_contains($view,'Definitief')&&str_contains($view,'In optie')&&str_contains($view,'Prognose'),'Scopebediening ontbreekt.');
$assert(str_contains($view,'aria-current')&&str_contains($view,'Vorige')&&str_contains($view,'Volgende'),'Toegankelijke paginering ontbreekt.');
$assert(str_contains($view,'exportLoading.value||!bookings.value?.pagination.totalItems')&&str_contains($service,'bookingRevenueExportUrl'),'Exportbeveiliging of volledige exportcriteria ontbrekenekt.');
echo "Booking revenue frontend contract tests passed.\n";
