<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/vendor/autoload.php';

use GeoFort\Booking\BookingPolicy;
use GeoFort\Booking\Stored\StoredBookingAssembler;
use GeoFort\Booking\Validation\BookingValidationCoordinator;
use GeoFort\Services\Booking\Catering\{BookingCateringChangeCode,BookingCateringChangeCommand,BookingCateringChangeService,BookingCateringValues};
use GeoFort\Services\Booking\Data\FoodAndDrinkSelectionData;
use GeoFort\Services\Sql\{BookingCateringSqlRepository,BookingChangeHistorySqlRepository,StoredBookingSqlRepository};

$env=[];foreach(['HOST','PORT','NAME','USER'] as $key){$value=getenv('STATUS_TEST_DB_'.$key);if($value===false){fwrite(STDERR,"FAIL: STATUS_TEST_DB_{$key} ontbreekt.\n");exit(2);}$env[$key]=(string)$value;}
if(getenv('STATUS_TEST_DB_CONFIRM')!=='YES_DISPOSABLE'||preg_match('/(test|tmp|scratch|disposable)/i',$env['NAME'])!==1||strtolower((string)getenv('APP_ENV'))==='production'){fwrite(STDERR,"FAIL: integratietest weigert niet-aantoonbaar wegwerpbare database.\n");exit(2);}
$pdo=new PDO(sprintf('mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4',$env['HOST'],$env['PORT'],$env['NAME']),$env['USER'],(string)(getenv('STATUS_TEST_DB_PASSWORD')?:''),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$tables=['booking_change_history','booking_status_history','booking_rule_overrides','booking_day_settings','aanvraag_onderwijs_selecties','aanvragen','admin_users'];
$cleanup=static function()use($pdo,$tables):void{$pdo->exec('SET FOREIGN_KEY_CHECKS=0');try{foreach($tables as $table)$pdo->exec("DROP TABLE IF EXISTS {$table}");}finally{$pdo->exec('SET FOREIGN_KEY_CHECKS=1');}};
$cleanup();$exit=0;
try{
$pdo->exec("CREATE TABLE aanvragen(id INT AUTO_INCREMENT PRIMARY KEY,status ENUM('In optie','Definitief','Afgewezen') NOT NULL,schoolnaam VARCHAR(255) NOT NULL,land VARCHAR(32) NOT NULL,adres VARCHAR(255) NOT NULL,postcode VARCHAR(16) NOT NULL,plaats VARCHAR(120) NOT NULL,school_telefoonnummer VARCHAR(25) NOT NULL,contactpersoon_telefoonnummer VARCHAR(25) NOT NULL,contactpersoon_voornaam VARCHAR(255) NOT NULL,contactpersoon_achternaam VARCHAR(255) NOT NULL,email VARCHAR(255) NOT NULL,bezoekdatum DATE NOT NULL,hoe_kent_u_geofort VARCHAR(120),opmerkingen TEXT,cjpPasGebruik ENUM('ja','nee') NOT NULL,cjpContactpersoonNaam VARCHAR(80),cjpPasnummer VARCHAR(9),onderwijs_sector VARCHAR(40) NOT NULL,programma VARCHAR(20) NOT NULL,keuzemodule_key VARCHAR(120),aantal_leerlingen INT,aantal_begeleiders INT,remise_break INT NOT NULL DEFAULT 0,kazerne_break INT NOT NULL DEFAULT 0,fortgracht_break INT NOT NULL DEFAULT 0,glas_limonade INT NOT NULL DEFAULT 0,waterijsje INT NOT NULL DEFAULT 0,remise_lunch INT NOT NULL DEFAULT 0,eigen_picknick TINYINT(1) NOT NULL DEFAULT 0,voorwaarden_akkoord TINYINT(1) NOT NULL,voorwaarden_akkoord_op DATETIME,source_system VARCHAR(80),source_record_id BIGINT,source_record_checksum CHAR(64),source_import_run_id BIGINT) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE admin_users(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190),name VARCHAR(120),role VARCHAR(50),password_hash VARCHAR(255),is_active TINYINT DEFAULT 1,created_at DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE aanvraag_onderwijs_selecties(id INT AUTO_INCREMENT PRIMARY KEY,aanvraag_id INT NOT NULL,sector_key VARCHAR(40),level_key VARCHAR(80),group_key VARCHAR(80),level_position INT,group_position INT,FOREIGN KEY(aanvraag_id) REFERENCES aanvragen(id)) ENGINE=InnoDB");
$sqlRoot=dirname(__DIR__,2).'/database/sql/';foreach(['2026-07-17_create_booking_day_settings.sql','2026-07-18_create_booking_status_history.sql','2026-07-21_create_booking_rule_overrides.sql','2026-07-22_create_booking_change_history.sql','2026-07-22_link_overrides_to_change_history.sql'] as $migration)$pdo->exec((string)file_get_contents($sqlRoot.$migration));
$pdo->exec("INSERT INTO admin_users(email,name,role,password_hash)VALUES('catering@example.test','Catering','admin','x')");$admin=(int)$pdo->lastInsertId();
$insert=static function(string $status,int $lunch=0,bool $picnic=false)use($pdo):int{$statement=$pdo->prepare("INSERT INTO aanvragen(status,schoolnaam,land,adres,postcode,plaats,school_telefoonnummer,contactpersoon_telefoonnummer,contactpersoon_voornaam,contactpersoon_achternaam,email,bezoekdatum,cjpPasGebruik,onderwijs_sector,programma,keuzemodule_key,aantal_leerlingen,aantal_begeleiders,remise_lunch,eigen_picknick,voorwaarden_akkoord,voorwaarden_akkoord_op)VALUES(:status,'School','NL','A','1','P','1','2','V','N','a@example.test','2026-09-01','nee','primairOnderwijs','dag','Earth-Watch',50,7,:lunch,:picnic,1,NOW())");$statement->execute([':status'=>$status,':lunch'=>$lunch,':picnic'=>$picnic?1:0]);$id=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO aanvraag_onderwijs_selecties(aanvraag_id,sector_key,level_key,group_key,level_position,group_position)VALUES(:id,'primairOnderwijs','regulier','groep5',1,1)")->execute([':id'=>$id]);return $id;};
$service=static fn()=>new BookingCateringChangeService($pdo,new StoredBookingSqlRepository($pdo,new StoredBookingAssembler()),new BookingCateringSqlRepository($pdo),new BookingChangeHistorySqlRepository($pdo),new BookingValidationCoordinator());
$change=static function(int $id,BookingCateringValues $expected,FoodAndDrinkSelectionData $proposed)use($service,$admin){return $service()->change(new BookingCateringChangeCommand($id,$expected,$proposed,$admin));};
$empty=new BookingCateringValues(0,0,0,0,0,0,false);$picnic=new FoodAndDrinkSelectionData(1,0,0,0,0,'eigen_picknick',0,true);
$assert=static function(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);};
foreach([BookingPolicy::STATUS_OPTION,BookingPolicy::STATUS_CONFIRMED,BookingPolicy::STATUS_REJECTED] as $status){$id=$insert($status);$result=$change($id,$empty,$picnic);$row=$pdo->query("SELECT * FROM aanvragen WHERE id={$id}")->fetch();$assert($result->code===BookingCateringChangeCode::Success&&$row['status']===$status&&(int)$row['remise_break']===1&&(int)$row['eigen_picknick']===1,"Wijziging/status faalt voor {$status}.");$audit=$pdo->query("SELECT * FROM booking_change_history WHERE booking_id={$id}")->fetch();$assert($audit['change_type']==='catering_changed','Audit change_type onjuist.');$fields=json_decode($audit['changed_fields_json'],true,512,JSON_THROW_ON_ERROR);$assert(array_keys($fields)===['remise_break','eigen_picknick']&&$fields['eigen_picknick']['before']===false&&$fields['eigen_picknick']['after']===true,'Audit bevat niet uitsluitend echte int/bool-wijzigingen.');}
$id=$insert(BookingPolicy::STATUS_OPTION,0,true);$expectedPicnic=new BookingCateringValues(0,0,0,0,0,0,true);$assert($change($id,$expectedPicnic,new FoodAndDrinkSelectionData(0,0,0,0,0,'eigen_picknick',0,true))->code===BookingCateringChangeCode::NoCateringChange,'No-opcode onjuist.');$assert((int)$pdo->query("SELECT COUNT(*) FROM booking_change_history WHERE booking_id={$id}")->fetchColumn()===0,'No-op schrijft audit.');
$id=$insert(BookingPolicy::STATUS_OPTION);$assert($change($id,new BookingCateringValues(9,0,0,0,0,0,false),$picnic)->code===BookingCateringChangeCode::CateringConflict,'Expected conflict ontbreekt.');$assert((int)$pdo->query("SELECT COUNT(*) FROM booking_change_history WHERE booking_id={$id}")->fetchColumn()===0,'Conflict muteert audit.');
$id=$insert(BookingPolicy::STATUS_OPTION);$invalid=new FoodAndDrinkSelectionData(201,0,0,0,0,'eigen_picknick',0,true);$assert($change($id,$empty,$invalid)->code===BookingCateringChangeCode::InvalidCateringSelection,'Ongeldige selectie wordt gemuteerd.');
$id=$insert(BookingPolicy::STATUS_OPTION);$assert($change($id,$empty,new FoodAndDrinkSelectionData(0,0,0,0,0,'remise_lunch',50,false))->code===BookingCateringChangeCode::Success,'0/0 kan niet naar Remiselunch worden hersteld.');
$id=$insert(BookingPolicy::STATUS_OPTION,50,true);$conflictExpected=new BookingCateringValues(0,0,0,0,0,50,true);$assert($change($id,$conflictExpected,new FoodAndDrinkSelectionData(0,0,0,0,0,'eigen_picknick',0,true))->code===BookingCateringChangeCode::Success,'Conflictdata kan niet worden hersteld.');
$assert($change(999999,$empty,$picnic)->code===BookingCateringChangeCode::BookingNotFound,'Onbekende bookingcode onjuist.');
$id=$insert(BookingPolicy::STATUS_OPTION);$pdo->exec('ALTER TABLE booking_rule_overrides DROP FOREIGN KEY fk_booking_rule_overrides_change_history');$pdo->exec('DROP TABLE booking_change_history');$assert($change($id,$empty,$picnic)->code===BookingCateringChangeCode::DatabaseError,'Auditfout geeft geen databasefout.');$assert((int)$pdo->query("SELECT remise_break FROM aanvragen WHERE id={$id}")->fetchColumn()===0,'Auditfout rolt update niet terug.');
$assert((int)$pdo->query('SELECT COUNT(*) FROM booking_status_history')->fetchColumn()===0,'Statushistory geschreven.');$assert((int)$pdo->query('SELECT COUNT(*) FROM booking_rule_overrides')->fetchColumn()===0,'Override geschreven.');$assert((int)$pdo->query('SELECT COUNT(*) FROM booking_day_settings')->fetchColumn()===0,'Daginstellingen geschreven.');
echo "Booking catering MariaDB integration tests passed.\n";
}catch(Throwable $exception){fwrite(STDERR,"FAIL: {$exception->getMessage()}\n");$exit=1;}finally{$cleanup();}
exit($exit);
