import fs from "node:fs";
import ts from "typescript";
const root = new URL("../../", import.meta.url);
const overview = fs.readFileSync(new URL("resources/js/admin/components/calendar/DashboardCalendarOverview.vue", root), "utf8");
const page = fs.readFileSync(new URL("resources/js/admin/views/DashboardCalendarView.vue", root), "utf8");
const api = fs.readFileSync(new URL("resources/js/admin/services/dashboardCalendarOverviewApi.ts", root), "utf8");
const dayCell = fs.readFileSync(new URL("resources/js/admin/components/calendar/DashboardCalendarOverviewDayCell.vue", root), "utf8");
const helperSource = fs.readFileSync(new URL("resources/js/admin/utils/calendarOverviewPresentation.ts", root), "utf8");
const helperJs = ts.transpileModule(helperSource, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const helper = await import(`data:text/javascript;base64,${Buffer.from(helperJs).toString("base64")}`);
const assert = (condition, message) => { if (!condition) throw new Error(message); };
assert(page.includes('route.query.mode === "management" ? "management" : "overview"'), "Ongeldige/ontbrekende mode normaliseert niet naar overview.");
assert(overview.includes('watch(visibleMonth') && overview.includes('fetchDashboardCalendarOverview'), "Maandwisseling laadt niet.");
assert(!overview.includes('watch(programFilter') && !overview.includes('watch(statusFilter'), "Filters mogen geen requestwatchers hebben.");
assert(overview.includes('programFilter.value = "all"') && overview.includes('statusFilter.value = "all"'), "Reset ontbreekt.");
assert(api.includes("cache.set") && api.includes("cache.delete"), "Cache of invalidatie ontbreekt.");
assert(helper.calendarOverviewDayStatusClass("confirmed") === "has-status-confirmed", "Definitief-accent klopt niet.");
assert(helper.calendarOverviewDayStatusClass("option") === "has-status-option", "Optie-accent klopt niet.");
assert(helper.calendarOverviewDayStatusClass("rejected") === "has-status-rejected", "Afgewezen-accent klopt niet.");
assert(helper.calendarOverviewBookingCountClass(1) === "has-single-booking", "Eén aanvraag is niet single.");
assert(helper.calendarOverviewBookingCountClass(2) === "has-multiple-bookings" && helper.calendarOverviewBookingCountClass(3) === "has-multiple-bookings", "Twee of meer aanvragen zijn niet multiple.");
assert(helper.calendarOverviewBookingCountClass(0) === null, "Lege resultaten krijgen een bookingaccent.");
const capacity = { totalDaily: 200, programs: { dag: 150, ochtend: 75 } };
assert(helper.effectiveCalendarOverviewCapacity(capacity, "dag") === capacity.programs.dag, "Dag gebruikt niet de Dag-capaciteit.");
assert(helper.effectiveCalendarOverviewCapacity(capacity, "ochtend") === capacity.programs.ochtend, "Ochtend gebruikt niet de Ochtend-capaciteit.");
assert(helper.effectiveCalendarOverviewCapacity(capacity, "all") === capacity.totalDaily, "Alle programma's gebruikt niet de centrale totale capaciteit.");
assert(helper.calendarOverviewOccupancyLevel(0, capacity.totalDaily) === "empty", "Nul leerlingen is niet empty.");
assert(helper.calendarOverviewOccupancyLevel(1, capacity.totalDaily) === "low", "Lage bezetting klopt niet.");
assert(helper.calendarOverviewOccupancyLevel(capacity.totalDaily / 2, capacity.totalDaily) === "medium", "Middelmatige bezetting klopt niet.");
assert(helper.calendarOverviewOccupancyLevel(capacity.totalDaily * 0.8, capacity.totalDaily) === "high", "Hoge bezetting klopt niet.");
assert(helper.calendarOverviewOccupancyLevel(capacity.totalDaily, capacity.totalDaily) === "full-or-over" && helper.calendarOverviewOccupancyLevel(capacity.totalDaily + 1, capacity.totalDaily) === "full-or-over", "Volledige of overschreden bezetting klopt niet.");
assert(dayCell.includes('invalid ? "minimaal " : ""') && dayCell.includes("zonder geldig aantal"), "Onbekende of ongeldige aantallen verliezen hun minimumwaarschuwing.");
assert(dayCell.includes("!props.day.disabled") && dayCell.includes("totalBookings.value > 0"), "Geblokkeerde of lege dagen kunnen een accent krijgen.");
process.stdout.write("Dashboard calendar overview interactions: OK\n");
