<?php
declare(strict_types=1);
if(PHP_VERSION_ID<80100){fwrite(STDERR,"SKIP: integratietest vereist expliciet PHP 8.1+.\n");exit(0);}

use GeoFort\Services\Migration\LegacyBookingImportService;
use GeoFort\Services\Migration\LegacyBookingMapper;
use GeoFort\Services\Migration\LegacyBookingRollbackService;
use GeoFort\Services\Migration\PdoLegacyMigrationTarget;
use GeoFort\Services\Migration\PdoLegacyRollbackTarget;
require dirname(__DIR__,2).'/vendor/autoload.php';

$keys=['HOST','PORT','NAME','USER'];$env=[];
foreach($keys as$key){$value=getenv('MIGRATION_TEST_DB_'.$key);if($value===false){fwrite(STDOUT,"SKIP: geen expliciete MIGRATION_TEST_DB_* configuratie; MariaDB-integratietest niet uitgevoerd.\n");exit(0);}$env[$key]=(string)$value;}
$password=getenv('MIGRATION_TEST_DB_PASSWORD');$env['PASSWORD']=$password===false?'':(string)$password;
$name=strtolower($env['NAME']);
if(!preg_match('/(test|tmp|scratch|throwaway|disposable)/',$name)||getenv('MIGRATION_TEST_DB_CONFIRM')!=='YES_DISPOSABLE'||strtolower((string)getenv('APP_ENV'))==='production'){fwrite(STDERR,"FAIL: integratietest weigert niet-aantoonbaar wegwerpbare of productieachtige configuratie.\n");exit(2);}
$pdo=new PDO(sprintf('mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4',$env['HOST'],$env['PORT'],$env['NAME']),$env['USER'],$env['PASSWORD'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
fwrite(STDOUT,'Database VERSION(): '.(string)$pdo->query('SELECT VERSION()')->fetchColumn()."\n");
fwrite(STDOUT,'Database @@version_comment: '.(string)$pdo->query('SELECT @@version_comment')->fetchColumn()."\n");

$runSql=static function(PDO$pdo,string$path):void{$delimiter=';';$buffer='';foreach(file($path,FILE_IGNORE_NEW_LINES)as$line){$trim=trim($line);if(strpos($trim,'--')===0||$trim==='')continue;if(strpos($trim,'DELIMITER ')===0){$delimiter=trim(substr($trim,10));continue;}$buffer.=$line."\n";if(substr(rtrim($buffer),-strlen($delimiter))===$delimiter){$statement=substr(rtrim($buffer),0,-strlen($delimiter));$pdo->exec($statement);$buffer='';}}if(trim($buffer)!=='')throw new RuntimeException('Onvolledig SQL-bestand.');};
$root=dirname(__DIR__,2);$forward=$root.'/database/sql/2026-07-15_add_legacy_booking_import_tracking.sql';$trackingRollback=$root.'/database/sql/2026-07-15_rollback_legacy_booking_import_tracking.sql';
$resetDisposableSchema=static function(PDO$pdo,array$env):void{
    $expected=$env['NAME'];$actual=(string)$pdo->query('SELECT DATABASE()')->fetchColumn();$confirmed=getenv('MIGRATION_TEST_DB_CONFIRM')==='YES_DISPOSABLE';$safeName=preg_match('/(test|disposable)/i',$expected)===1;$notProduction=strtolower((string)getenv('APP_ENV'))!=='production';
    if(!$confirmed||!$safeName||!$notProduction||$actual!==$expected)throw new RuntimeException('Disposable reset geweigerd: veiligheidscontext is niet meer geldig.');
    $exists=static function(string$sql)use($pdo):bool{return(int)$pdo->query($sql)->fetchColumn()>0;};
    if($exists("SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='aanvragen' AND CONSTRAINT_NAME='fk_aanvragen_source_import_run' AND CONSTRAINT_TYPE='FOREIGN KEY'"))$pdo->exec('ALTER TABLE `aanvragen` DROP FOREIGN KEY `fk_aanvragen_source_import_run`');
    if($exists("SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='aanvragen' AND INDEX_NAME='idx_aanvragen_source_import_run'"))$pdo->exec('ALTER TABLE `aanvragen` DROP INDEX `idx_aanvragen_source_import_run`');
    if($exists("SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='aanvragen' AND INDEX_NAME='uniq_aanvragen_source_record'"))$pdo->exec('ALTER TABLE `aanvragen` DROP INDEX `uniq_aanvragen_source_record`');
    foreach(['source_import_run_id','source_record_checksum','source_record_id','source_system']as$column){$quoted=$pdo->quote($column);if($exists("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='aanvragen' AND COLUMN_NAME={$quoted}"))$pdo->exec("ALTER TABLE `aanvragen` DROP COLUMN `{$column}`");}
    if($exists("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='legacy_booking_import_runs'"))$pdo->exec('DROP TABLE `legacy_booking_import_runs`');
    foreach(['aanvraag_onderwijs_selecties','aanvragen','form_submit_log']as$table){$quoted=$pdo->quote($table);if($exists("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME={$quoted}"))$pdo->exec("DROP TABLE `{$table}`");}
};
$createBase=static function(PDO$pdo):void{$pdo->exec("CREATE TABLE aanvragen (id INT NOT NULL AUTO_INCREMENT,status VARCHAR(20),schoolnaam VARCHAR(255),land VARCHAR(32),adres VARCHAR(255),postcode VARCHAR(16),plaats VARCHAR(120),school_telefoonnummer VARCHAR(25),contactpersoon_telefoonnummer VARCHAR(25),contactpersoon_voornaam VARCHAR(255),contactpersoon_achternaam VARCHAR(255),email VARCHAR(255),bezoekdatum DATE,hoe_kent_u_geofort VARCHAR(120),opmerkingen TEXT,cjpPasGebruik VARCHAR(3),cjpContactpersoonNaam VARCHAR(80),cjpPasnummer VARCHAR(9),onderwijs_sector VARCHAR(40),programma VARCHAR(20),keuzemodule_key VARCHAR(120),aantal_leerlingen INT UNSIGNED,aantal_begeleiders INT UNSIGNED,remise_break INT UNSIGNED,kazerne_break INT UNSIGNED,fortgracht_break INT UNSIGNED,glas_limonade INT UNSIGNED,waterijsje INT UNSIGNED,remise_lunch INT UNSIGNED,eigen_picknick TINYINT,voorwaarden_akkoord TINYINT,voorwaarden_akkoord_op DATETIME,PRIMARY KEY(id)) ENGINE=InnoDB");$pdo->exec("CREATE TABLE aanvraag_onderwijs_selecties (id INT NOT NULL AUTO_INCREMENT,aanvraag_id INT NOT NULL,sector_key VARCHAR(40),sector_label VARCHAR(120),level_key VARCHAR(80),level_label VARCHAR(160),level_position TINYINT UNSIGNED,group_key VARCHAR(80),group_label VARCHAR(160),group_position TINYINT UNSIGNED,PRIMARY KEY(id),UNIQUE KEY uq_sel(aanvraag_id,level_key,group_key),CONSTRAINT fk_sel FOREIGN KEY(aanvraag_id) REFERENCES aanvragen(id) ON DELETE CASCADE) ENGINE=InnoDB");$pdo->exec('CREATE TABLE form_submit_log (id INT NOT NULL AUTO_INCREMENT, marker VARCHAR(40), PRIMARY KEY(id)) ENGINE=InnoDB');};
$createTracking=static function(PDO$pdo):void{$pdo->exec("CREATE TABLE legacy_booking_import_runs (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,source_system VARCHAR(80) NOT NULL,source_filename VARCHAR(255) NOT NULL,source_checksum CHAR(64) NOT NULL,started_at DATETIME NOT NULL,completed_at DATETIME NULL,status ENUM('running','completed') NOT NULL DEFAULT 'running',imported_count INT UNSIGNED NOT NULL DEFAULT 0,skipped_count INT UNSIGNED NOT NULL DEFAULT 0,warning_count INT UNSIGNED NOT NULL DEFAULT 0,PRIMARY KEY(id),KEY idx_legacy_import_source_checksum(source_system,source_checksum)) ENGINE=InnoDB");};
$assertTracking=static function(PDO$pdo):void{$columns=(int)$pdo->query("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='aanvragen' AND COLUMN_NAME IN ('source_system','source_record_id','source_record_checksum','source_import_run_id')")->fetchColumn();$indexes=(int)$pdo->query("SELECT COUNT(DISTINCT INDEX_NAME) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='aanvragen' AND INDEX_NAME IN ('uniq_aanvragen_source_record','idx_aanvragen_source_import_run')")->fetchColumn();$fk=(int)$pdo->query("SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND TABLE_NAME='aanvragen' AND CONSTRAINT_NAME='fk_aanvragen_source_import_run' AND CONSTRAINT_TYPE='FOREIGN KEY'")->fetchColumn();$table=(int)$pdo->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='legacy_booking_import_runs'")->fetchColumn();if([$columns,$indexes,$fk,$table]!==[4,2,1,1])throw new RuntimeException('Tracking-schema is onvolledig.');};
$reset=static function()use($pdo,$env,$resetDisposableSchema,$createBase):void{$resetDisposableSchema($pdo,$env);$createBase($pdo);};
$assertResetClean=static function(PDO$pdo):void{$tracking=(int)$pdo->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='legacy_booking_import_runs'")->fetchColumn();$columns=(int)$pdo->query("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='aanvragen' AND COLUMN_NAME IN ('source_system','source_record_id','source_record_checksum','source_import_run_id')")->fetchColumn();if($tracking!==0||$columns!==0)throw new RuntimeException('Disposable reset liet trackingobjecten achter.');};

// Regressies voor lege en gedeeltelijk uitgevoerde forwardmigraties.
$reset();$runSql($pdo,$forward);$assertTracking($pdo);fwrite(STDOUT,"Forward scenario leeg schema: OK\n");
$runSql($pdo,$forward);$assertTracking($pdo);fwrite(STDOUT,"Forward tweede run: OK\n");
$resetDisposableSchema($pdo,$env);$assertResetClean($pdo);fwrite(STDOUT,"Reset na volledige forwardmigratie: OK\n");
$resetDisposableSchema($pdo,$env);$assertResetClean($pdo);fwrite(STDOUT,"Reset tweemaal achter elkaar: OK\n");
$createTracking($pdo);$resetDisposableSchema($pdo,$env);$assertResetClean($pdo);fwrite(STDOUT,"Reset met alleen trackingtabel: OK\n");
$reset();$createTracking($pdo);$runSql($pdo,$forward);$assertTracking($pdo);fwrite(STDOUT,"Forward bestaande trackingtabel: OK\n");
$reset();$createTracking($pdo);$pdo->exec('ALTER TABLE aanvragen ADD COLUMN source_system VARCHAR(80) NULL');$runSql($pdo,$forward);$assertTracking($pdo);fwrite(STDOUT,"Forward één bestaande kolom: OK\n");
$resetDisposableSchema($pdo,$env);$assertResetClean($pdo);fwrite(STDOUT,"Reset na gedeeltelijke forwardmigratie: OK\n");
$reset();$createTracking($pdo);$pdo->exec('ALTER TABLE aanvragen ADD COLUMN source_system VARCHAR(80) NULL, ADD COLUMN source_record_id BIGINT UNSIGNED NULL, ADD COLUMN source_record_checksum CHAR(64) NULL, ADD COLUMN source_import_run_id BIGINT UNSIGNED NULL');$runSql($pdo,$forward);$assertTracking($pdo);fwrite(STDOUT,"Forward alle bestaande kolommen: OK\n");
$reset();$createTracking($pdo);$pdo->exec('ALTER TABLE aanvragen ADD COLUMN source_system VARCHAR(80) NULL, ADD COLUMN source_record_id BIGINT UNSIGNED NULL, ADD COLUMN source_record_checksum CHAR(64) NULL, ADD COLUMN source_import_run_id BIGINT UNSIGNED NULL, ADD UNIQUE INDEX uniq_aanvragen_source_record(source_system,source_record_id)');$runSql($pdo,$forward);$assertTracking($pdo);fwrite(STDOUT,"Forward bestaande unieke index: OK\n");
$reset();$createTracking($pdo);$pdo->exec('ALTER TABLE aanvragen ADD COLUMN source_system VARCHAR(80) NULL, ADD COLUMN source_record_id BIGINT UNSIGNED NULL');$runSql($pdo,$forward);$assertTracking($pdo);fwrite(STDOUT,"Forward onderbroken migratie hervat: OK\n");
$runSql($pdo,$forward);$assertTracking($pdo);fwrite(STDOUT,"Forward bestaande foreign key: OK\n");
$pdo->exec('ALTER TABLE aanvragen DROP FOREIGN KEY fk_aanvragen_source_import_run');$resetDisposableSchema($pdo,$env);$assertResetClean($pdo);fwrite(STDOUT,"Reset wanneer foreign key ontbreekt: OK\n");
$reset();$runSql($pdo,$forward);$assertTracking($pdo);

// Volledig productiepad op het disposable schema.
$pdo->exec("INSERT INTO aanvragen(status,schoolnaam,land,adres,postcode,plaats,school_telefoonnummer,contactpersoon_telefoonnummer,contactpersoon_voornaam,contactpersoon_achternaam,email,bezoekdatum,onderwijs_sector,programma,cjpPasGebruik,remise_break,kazerne_break,fortgracht_break,glas_limonade,waterijsje,remise_lunch,eigen_picknick,voorwaarden_akkoord) VALUES('In optie','native','Nederland','x','x','x','x','x','x','x','native@example.test','2026-01-01','primairOnderwijs','dag','nee',0,0,0,0,0,0,0,0)");$nativeId=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO form_submit_log(marker) VALUES('keep')");
$legacy=['id'=>12,'status'=>'Definitief','schoolnaam'=>'synthetic','adres'=>'x','postcode'=>'1234 AB','plaats'=>'x','school_telefoon'=>'1','contact_telefoon'=>'2','voornaam_contactpersoon'=>'x','achternaam_contactpersoon'=>'x','email'=>'synthetic@example.test','bezoekdatum'=>'2026-09-01','hoe_kent_u_geofort'=>'test','cjp_korting'=>0,'schooltype'=>'Primair Onderwijs','programma_duur'=>'dag','niveau1'=>'regulier','niveau2'=>'','niveau3'=>'','leeftijdsgroep1'=>'Groep 5','leeftijdsgroep2'=>'','leeftijdsgroep3'=>'','leeftijdsgroep4'=>'','leeftijdsgroep5'=>'','keuze_module'=>'Earth-Watch','aantal_leerlingen'=>40,'aantal_begeleiders'=>4,'remise_break'=>0,'kazerne_break'=>0,'fortgracht_break'=>0,'waterijsje'=>0,'glas_limonade'=>0,'remise_lunch'=>0,'eigen_picknick'=>0,'opmerkingen'=>'test'];$mapped=(new LegacyBookingMapper())->map($legacy);$item=['legacy_id'=>12,'source_checksum'=>str_repeat('a',64),'booking'=>$mapped['booking'],'selections'=>$mapped['selections']];
$service=new LegacyBookingImportService();$target=new PdoLegacyMigrationTarget($pdo);$first=$service->execute([$item],$target,'synthetic.sql',str_repeat('b',64),0);$importedId=(int)$pdo->query("SELECT id FROM aanvragen WHERE source_record_id=12")->fetchColumn();if($importedId===$nativeId||$importedId===12)throw new RuntimeException('Doel-ID is niet gegenereerd.');if((int)$pdo->query("SELECT aanvraag_id FROM aanvraag_onderwijs_selecties WHERE aanvraag_id={$importedId}")->fetchColumn()!==$importedId)throw new RuntimeException('Selectie-FK onjuist.');fwrite(STDOUT,"Eerste import: OK\n");
$second=$service->execute([$item],$target,'synthetic.sql',str_repeat('b',64),0);if($second['skipped']!==1)throw new RuntimeException('Herimport is niet overgeslagen.');fwrite(STDOUT,"Tweede identieke import: overgeslagen\n");
$changed=$item;$changed['source_checksum']=str_repeat('c',64);try{$service->execute([$changed],$target,'synthetic.sql',str_repeat('c',64),0);throw new RuntimeException('Gewijzigde checksum blokkeerde niet.');}catch(RuntimeException$e){if(strpos($e->getMessage(),'Gewijzigde')===false)throw$e;}
$bad=$item;$bad['legacy_id']=13;$bad['source_checksum']=str_repeat('d',64);$bad['selections'][]=$bad['selections'][0];try{$service->execute([$bad],$target,'synthetic.sql',str_repeat('d',64),0);}catch(Throwable$e){}if((int)$pdo->query("SELECT COUNT(*) FROM aanvragen WHERE source_record_id=13")->fetchColumn()!==0)throw new RuntimeException('Echte rollback faalde.');if((string)$pdo->query('SELECT marker FROM form_submit_log')->fetchColumn()!=='keep')throw new RuntimeException('form_submit_log gewijzigd.');
$rollback=new LegacyBookingRollbackService();$rollbackTarget=new PdoLegacyRollbackTarget($pdo);$rollback->execute((int)$second['run_id'],$rollbackTarget);$rollback->execute((int)$first['run_id'],$rollbackTarget);if((int)$pdo->query("SELECT COUNT(*) FROM aanvragen WHERE id={$nativeId}")->fetchColumn()!==1)throw new RuntimeException('Native aanvraag verwijderd.');fwrite(STDOUT,"Runrollback: OK\n");
$runSql($pdo,$trackingRollback);fwrite(STDOUT,"Trackingrollback: OK\n");$resetDisposableSchema($pdo,$env);fwrite(STDOUT,"OK: MariaDB/MySQL-integratietest geslaagd.\n");
